spring:
    application:
        name: GATEWAY-SERVICE
    cloud:
        gateway:
            routes:
                - id: order-service
                  uri: lb://ORDER-SERVICE
                  predicates:
                    - Path=/order/**
                  # filters:
                  #   - name: CircuitBreaker
                  #     args:
                  #       name: order-service
                  #       fallbackUri: forward:/orderFallBack
                - id: payment-service
                  uri: lb://PAYMENT-SERVICE
                  predicates:
                    - Path=/payment/**
                  # filters:
                  #   - name: CircuitBreaker
                  #     args:
                  #       name: payment-service
                  #       fallbackUri: forward:/paymentFallBack

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        hostname: localhost

server:
    port: 8989

#Expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000